config/routes.rb
Myrubyblog::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  root "home#index"

  resources :comments

  get "pages/about"
  get "pages/contact"
  get "pages/resources", ActiveAdmin::Devise.config
     
  resources :categories

  get "categories/index"
  get "categories/edit"
  get "categories/new"
  get "categories/show"

    resources :posts do
      member do
        post 'vote'
      end
    end
  resources :categories
  get "about", :to => "pages#about"
  get "contact", :to => "pages#contact"
  get "resources", :to => "pages#resources"
  ActiveAdmin.routes(self)

   
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	# attr_accessible :name
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	# attr_accessible :post_id, :name, :email, :body, :post
  	belongs_to :post
  	validates_presence_of :name
  	validates_length_of :name, :within =>2..20
  	validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
	# attr_accessible :title, :body, :category_id, :admin_user_id
	mount_uploader :picture, PictureUploader
	default_scope order('created_at DESC')#?
	belongs_to :category
	belongs_to :admin_user
	has_many :comments, :dependent => :destroy
	has_many :votes, :dependent => :destroy
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :all_categories
  helper_method :all_posts
  before_filter :site_search

  def all_categories
  	@categories = Category.all
  end
  def all_posts
  	@posts = Post.all
  end
  def site_search
    @q = Post.search(params[:q])
    @search_posts = @q.result(distinct: true)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts
  end

  def new
  	@category = Category.new
  end

  def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "您的文章類別儲存成功！"
			redirect_to @category
		else
			render "new"
		end
	end
  
  def edit
		@category = Category.find(params[:id])
  end
  
  def update
		@category = Category.find(category_params)
		@user = AdminUser.all
		if @category.update_attributes(params[:post])
			redirect_to category_path, :notice => "您的文章類別更新成功！"
		else
			render "edit"
		end
  end

	private
	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
	def create
		@comment = Comment.new(comment_params)
		if @comment.save
			flash[:notice] = '您的回應儲存成功！'
			redirect_to(@comment.post)
		else
			flash[:notice] = "您的回應儲存失敗： #{@comment.errors}"
			redirect_to(@comment.post)
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:post_id,:name,:email,:body)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@posts = Post.all
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@q = Post.search(params[:q])
		@posts = @q.result(distinct: true)
	end

	def new
		@post = Post.new
		@category = Category.all
		@user = AdminUser.all
	end
	
	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:success] = "您的文章儲存成功！"
			redirect_to @post
		else
			render "new"
		end
	end

	def edit
		@post = Post.find(params[:id])
	end
	
	def update
		@post = Post.find(post_params)
		@user = AdminUser.all
		if @post.update_attributes(params[:post])
			redirect_to post_path, :notice => "您的文章更新成功！"
		else
			render "edit"
		end
	end
	
	def show
		@post = Post.find(params[:id])
		@user = AdminUser.all
		@comment = @post.comments.build()
	end
	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end
	
	def vote
		@post = Post.find(params[:id])
		@post.votes.create
		redirect_to request.referer
		#回到該頁面
	end

	private
	def post_params
		params.require(:post).permit(:title, :body, :picture, :category_id, :admin_user_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<div class="post">
	<h2 class="title">Listing categories</h2>
	<div class="entry">
	    <% @categories.each do |category| %>
	        <p><%= link_to category.name, category %></p>
	    <% end %>
		<p class="links"><%= link_to "回到文章列表", posts_path %></p>
	</div>
</div>

app/views/categories/show.html.erb
<% if @posts.each do |post| %>
	<div class="post">
		<h2 class="title"><%= link_to post.title, post %> </h2>
		<div class="entry"><p><%= post.body %></p></div>
		<div class="byline">
			<p class="meta"><%= post.created_at.strftime("%b %d. %Y") %>
				Posted by <%= post.admin_user.name %></p>
			<p class="links"><%= link_to "Read More..", post %>
				&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
			Vote :<%= post.votes.count %>
			<%= button_to '+1', vote_post_path(post), method: :post %></p>
		</div>
	</div>
<% end.empty? %>
	<div class="post">
		<div class="entry"><p>Sorry, 這個類別中沒有文章！</p></div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th>Post</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.email %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
<div class="post">
	<h2 class="title"><%= link_to post.title, post %> </h2>
	<div class="entry">
		<p><%= truncate(post.body, length: 100) %></p>
		<!-- 切斷過長的文字 -->
	</div>
	<div class="byline">
		<p class="meta"><%= post.created_at.strftime("%b %d. %Y") %> Posted by <%= post.admin_user.name %></p>
		<p class="links"><%= link_to "Read More..", post %>
			&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
			Comments :<%= post.comments.count %>
			&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
			Vote :<%= post.votes.count %>
			<%= button_to '+1', vote_post_path(post), method: :post %>
		</p>
	</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
					<div class="flash-message">
						<% flash.each do |key,value| %>
							<p><%= value %></p>
						<% end %>
					</div>
					<%= yield %><!-- main view -->

					<div style="clear: both;">&nbsp;</div>
				</div>
				<!-- end #content -->
				<%= render "partials/sidebar" %>
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page -->
	<div id="footer">
		<p>&copy; 2014, Wake up! Wake up! - My Ruby Blog Sample Project</p>
	</div>
</div>
<!-- end #footer -->


</body>
</html>

app/views/pages/about.html.erb
<div class="post"><h2 class="title">關於這個部落格...</h2>
<div class="entry"><p>這是透過Udemy線上學習平台中所開設的「Ruby on Rails from Scratch」課程，一步步跟隨著老師的教學，所建構起來的部落格。</p></div>
</div>

app/views/pages/contact.html.erb
<div class="post"><h2 class="title">聯絡我...</h2>
<div class="entry"><p>GOOGLE:</p><br /><p>FACEBOOK:</p></div>
</div>

app/views/pages/resources.html.erb
<div class="post"><h2 class="title">其他資源...</h2>
<div class="entry"><p>GOOGLE:</p><br /><p>FACEBOOK:</p></div>
</div>

app/views/partials/_comment.html.erb
<div class="comment">
<strong><i><%= h comment.name %></i></strong><br />
<%= simple_format h(comment.body) %>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wake up! Wake up!</title>
  <link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1><%= link_to "Wake up! Wake up!", root_path %></h1>
				<p>About my second life</p>
			</div>
			<div id="menu">
				<ul class="main-nav">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Blog", posts_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
					<li><%= link_to "Resources", resources_path %></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- end #header -->

app/views/partials/_sidebar.html.erb
<div id="sidebar">
					<ul>
						<li>
							<div id="search" >
								<%= search_form_for @q do |f| %>
								<%= f.text_field :title_or_body_cont %>
								<%= f.submit "Search" %>
								<% end %>
							</div>
							<div style="clear: both;">&nbsp;</div>
						</li>
						<li>
							<h2>文章目錄</h2>
							<ul>
								<%  all_categories.each do |cat| %>
									<li><%= link_to cat.name, category_path(:id => cat.id) %></li>

								<% end %>
							</ul>
						</li>
						<li>
							<h2>文章列表</h2>
							<ul>
								<%  all_posts.each do |post| %>
									<li><%= link_to post.title, post_path(:id => post.id) %></li>

								<% end %>
							</ul>
						</li>
						<li>
							<h2>發表文章</h2>
							<ul>
								<li><%= link_to '(*)登入部落格', admin_root_path %></li>
								<li><%= link_to '直接發表文章', new_post_path %></li>
							</ul>
						</li>
					</ul>
				</div>
				<!-- end #sidebar -->

app/views/posts/edit.html.erb
<div class="post">
	<h2 class="title">編輯文章</h2>
	<div class="entry">
	<%= form_for @post do |f| %>
	
	<p>
		<%= f.label :title, '文章標題：' %><br />
		<%= f.text_field :title %><br />
	</p>
	<p>
		<%= f.label :body, '文章內容：' %><br />
		<%= f.text_area :body %><br />
	</p>
	<p>
		上傳圖片：<%= f.file_field :picture %>
	</p>
	<p>
		文章作者：<%= f.select :admin_user_id, AdminUser.all.collect {|x| [x.name, x.id]},{:include_blank => "Select One"} %><br />
	</p>
	<p>
		文章類別：<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]},{:include_blank => "Select One"} %><br />
	</p>
	<p>
		<%= f.submit "更新文章" %><br />
	</p>
	<% end %>
	<p class="links"><%= link_to '回到文章列表', posts_path %></p></div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post">
	<h2 class="title"><%= link_to post.title, post %> </h2>
	<div class="entry">
		<p><%= truncate(post.body, length: 100) %></p>
		<!-- 切斷過長的文字 -->
	</div>
	<div class="byline">
		<p class="meta"><%= post.created_at.strftime("%b %d. %Y") %> Posted by <%= post.admin_user.name %></p>
		<p class="links">
			<%= link_to "Read More..", post %>
			&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
			Comments :<%= post.comments.count %>
			&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
			Vote :<%= post.votes.count %>
			<%= button_to '+1', vote_post_path(post), method: :post %>
		</p>
	</div>
</div>
<% end %>

app/views/posts/new.html.erb
<div class="post">
	<h2 class="title">新增文章</h2>
	<div class="entry">
	<%= form_for @post do |f| %>
	
	<p>
		<%= f.label :title, '文章標題：' %><br />
		<%= f.text_field :title %><br />
	</p>
	<p>
		<%= f.label :body, '文章內容：' %><br />
		<%= f.text_area :body %><br />
	</p>
	<p>
		上傳圖片：<%= f.file_field :picture %>
	</p>
	<p>
		文章作者：<%= f.select :admin_user_id, AdminUser.all.collect {|x| [x.name, x.id]},{:include_blank => "Select One"} %><br />
	</p>
	<p>
		文章類別：<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]},{:include_blank => "Select One"} %><br />
	</p>
	<p>
		<%= f.submit "送出文章" %><br />
	</p>
	<% end %>
	<p class="links"><%= link_to '回到文章列表', posts_path %></p></div>
</div>

app/views/posts/show.html.erb
<div class="post">
	<h2 class="title"><%= @post.title %></h2>
	<p><br />
		Category: <%= link_to @post.category.name, category_path(:id => @post.category.id) %>
		<small>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
			<%= @post.created_at.strftime("%b %d. %Y") %>
			&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;
			<%= @post.admin_user.name %>
		</small>
	</p>

	<p><%= @post.body %></p><br />
	<%= image_tag @post.picture_url, width: '100%' if @post.picture? %>
	<br />
	<p>Vote : <%= @post.votes.count %>
	<%= button_to '+1', vote_post_path(@post), method: :post %></p>


	<p class="links"><%= link_to "回到文章列表", posts_path %></p>

	<%= render :partial => 'partials/comment', :collection => @post.comments %>

	<h3 class="title">給個回應</h3>

	<%= form_for(@comment) do |f| %>
	    <%= f.hidden_field :post_id %>
	    <p>
	    	<%= f.label :name %><br>
	    	<%= f.text_field :name %>
	    </p>
	    <p>
		    <%= f.label :email %><br>
		    <%= f.text_field :email %>
		</p>
		<p>
		    <%= f.label :body %><br>
		    <%= f.text_area :body %>
		</p>
		<p>
		    <%= f.submit "送出回應" %>
		</p>
	<% end %>
</div>